version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      DATABASE_DIALECT: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: "ev6d2dm2"
    ports:
      - 54321:5432
  server:
    build: server/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  client:
    build: client/
    restart: always
    ports: 
      - 3000:3000
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

